name: lint shellcheck

on:
  pull_request:
    paths:
      - '.github/workflows/lint-shellcheck.yml'
      - '*.sh'

jobs:
  lint-shellcheck:
    runs-on: ubuntu-22.04

    steps:
       - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

       - uses: reviewdog/action-shellcheck@v1.19.0
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           reporter: github-pr-check
