name: lint shellcheck

on:
  pull_request:
    paths:
      - '.github/workflows/lint-shellcheck.yml'
      - '*.sh'

jobs:
  lint-shellcheck:
    runs-on: ubuntu-22.04

    steps:
       - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

       - uses: reviewdog/action-shellcheck@v1.20.0
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           reporter: github-pr-check
