name: lint shellcheck

on:
  pull_request:
    paths:
      - '.github/workflows/lint-shellcheck.yml'
      - '*.sh'

jobs:
  lint-shellcheck:
    runs-on: ubuntu-22.04

    steps:
       - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

       - uses: reviewdog/action-shellcheck@v1.20.0
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           reporter: github-pr-check
